apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: dadjokes-hpa
  namespace: sre-techtask-mk
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dadjokes-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50